### ISSUE TITLE
Audit Related persister config changes

### ISSUE THREAD

**Issue by anirudh-0** [Selco-Foundation/E4H_Digital_Platform#789]
In all persister configs, add the following:

```yaml
isAuditEnabled: true
module: IncidentManagement | AssetManagement
objecIdJsonPath: $.id
tenantIdJsonPath: $.tenantId
auditAttributeBasePath: $.service
```

- choose one module as applicable
- objectIdJsonPath should match the id parameter for that object

Reference: https://github.com/pucardotorg/kerala-configs/blob/master/egov-persister/summons.yml
